# Generated by Django 5.2.4 on 2025-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.CharField(default="Unknown", max_length=200),
        ),
    ]
