# Generated by Django 5.2.4 on 2025-07-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_brand_alter_car_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars_photos"),
        ),
        migrations.AddField(
            model_name="car",
            name="plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
