# Generated by Django 5.2.4 on 2025-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_photo_car_plate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="cars/cars_photos"
            ),
        ),
    ]
